#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-clean] [-?]"
   echo ""
   echo "   Builds the MQTT simulator environment."
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

PADOGRID_COMMON_JAR_FILE_PATH=`ls $PADOGRID_HOME/lib/padogrid-common-*.jar`
PADOGRID_COMMON_JAR_FILE_NAME="`basename $PADOGRID_COMMON_JAR_FILE_PATH`"
PADOGRID_COMMON_NAME=${PADOGRID_COMMON_JAR_FILE_NAME%.jar}
ADDON_VERSION=${PADOGRID_COMMON_NAME#padogrid-common-}

PADOGRID_COMMON_JAR_FILE_PATH="$PADOGRID_HOME/lib/padogrid-common-$ADDON_VERSION.jar"
PADOGRID_MQTT_JAR_FILE_PATH="$PADOGRID_HOME/mosquitto/lib/padogrid-mqtt-$ADDON_VERSION.jar"

# Install padogrid to the local repo
mvn install:install-file -Dfile=$PADOGRID_COMMON_JAR_FILE_PATH -DgroupId=padogrid.addon \
    -DartifactId=padogrid-common -Dversion=$ADDON_VERSION -Dpackaging=jar
mvn install:install-file -Dfile=$PADOGRID_MQTT_JAR_FILE_PATH -DgroupId=padogrid.addon \
    -DartifactId=padogrid-mqtt -Dversion=$ADDON_VERSION -Dpackaging=jar

pushd $APP_DIR > /dev/null
mvn package
popd > /dev/null
