#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-clean] [-?]"
   echo ""
   echo "   Builds the MQTT simulator environment."
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

pushd $APP_DIR > /dev/null
sed -i$__SED_BACKUP -e "s|<padogrid.version>.*$|<padogrid.version>$PADOGRID_VERSION</padogrid.version>|g" pom.xml
popd > /dev/null

# Install the required padogrid packages to the local repo
installMavenPadogridJar padogrid-common
installMavenPadogridJar padogrid-mqtt

# Build app
pushd $APP_DIR > /dev/null
if [ "$CLEAN" == "true" ]; then
   rm $APP_DIR/lib/*
   mvn clean
else
   #mvn package -Dmaven.plugin.validation=brief
   mvn package
   cp $APP_DIR/lib/* $PADOGRID_WORKSPACE/lib/
fi

# Update MQTT config files that have the deprecated attributes
# v0.9.29
if [ $PADOGRID_MAJOR_VERSION_NUMBER -eq 0 ] && [ $PADOGRID_MINOR_VERSION_NUMBER -eq 9 ] &&  [ $PADOGRID_UPDATE_VERSION_NUMBER -lt 29 ]; then
   sed -i${__SED_BACKUP} -e 's|pluginName:.*$|pluginNames: [questdb]|' etc/mqttv5-questdb.yaml
   sed -i${__SED_BACKUP} -e 's|pluginName:.*$|pluginNames: [questdb]|' etc/mqttv5-simulator.yaml
fi

popd > /dev/null
