#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# LOG_FILE (See etc/log4j.properties)
if [[ ${OS_NAME} == CYGWIN* ]]; then
   LOG_FILE=$LOG_DIR\\$EXECUTABLE.log
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
else
   LOG_FILE=$LOG_DIR/$EXECUTABLE.log
fi
export LOG_FILE

# Topic prefix and config file path. Used by padogrid-mqtt containers.
if [ "$PADOGRID_TOPIC_PREFIX" == "" ]; then
   export PADOGRID_TOPIC_PREFIX="edge"
fi

PADOGRID_SIMULATOR_CONFIG_ARG=""
if [ "$CONFIG_ARG" == "" ] && [ "$PADOGRID_SIMULATOR_CONFIG_FILE" != "" ]; then
   PADOGRID_SIMULATOR_CONFIG_ARG="-config $PADOGRID_SIMULATOR_CONFIG_FILE"
fi

# Paho logging
PAHO_LOG_CONFIG_FILE="$APP_ETC_DIR/paho-logging-$EXECUTABLE.properties"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.config.file=$PAHO_LOG_CONFIG_FILE"

# log4j log file path
JAVA_OPTS="$JAVA_OPTS -Dpadogrid.mqtt.logfile=$LOG_FILE"

# Application executable name. Useful for displaying usage.
JAVA_OPTS="$JAVA_OPTS -Dexecutable.name=$EXECUTABLE"

# Application specifics
#
JAVA_OPTS="$JAVA_OPTS -Dpadogrid.mqtt.client.cluster.config.file=$APP_ETC_DIR/mqttv5-client.yaml"
JAVA_OPTS="$JAVA_OPTS -Dpadogrid.mqtt.simulator.config.file=$APP_ETC_DIR/simulator-padogrid.yaml"

# To suppress warning jdk11: "FileLock may stop working in future versions of Java #507"
if [[ "$JAVA_VERSION" != "1.8"* ]]; then
   JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
fi

"$JAVA" $JAVA_OPTS padogrid.simulator.DataFeedSimulator $PADOGRID_SIMULATOR_CONFIG_ARG "$@"
